In [1]:
### bodlogo1
my_array = [x for x in range(50, 101)]
my_array

[50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [4]:
# bodlogo 2
my_array = [1] * 10 + [0] * 10 + [6] * 10
my_array

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6]

In [5]:
import numpy as np
my_array = np.arange(20, 32).reshape(3, 4)
my_array

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [6]:
my_array = np.eye(3)
my_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
my_array = np.diag(np.arange(1, 6))
my_array

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [8]:
my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
total_sum = np.sum(my_array)
print(f"niilber: {total_sum}")

column_sums = np.sum(my_array, axis=0)
print(f"baganuud niilber: {column_sums}")

row_sums = np.sum(my_array, axis=1)
print(f"mornii niilber: {row_sums}")

niilber: 78
baganuud niilber: [15 18 21 24]
mornii niilber: [10 26 42]


In [9]:
player1_salary = np.array([60000, 62000, 64000, 66000, 68000, 70000, 72000, 74000, 76000, 78000])
player1_appearances = np.array([20, 25, 22, 24, 26, 28, 30, 32, 35, 38])
player1_goals = np.array([5, 7, 6, 8, 9, 10, 11, 12, 14, 16])

player2_salary = np.array([55000, 58000, 60000, 62000, 64000, 66000, 68000, 70000, 72000, 74000])
player2_appearances = np.array([18, 22, 24, 20, 26, 28, 32, 34, 30, 36])
player2_goals = np.array([4, 6, 7, 5, 8, 9, 10, 12, 11, 14])

player3_salary = np.array([70000, 72000, 74000, 76000, 78000, 80000, 82000, 84000, 86000, 88000])
player3_appearances = np.array([24, 26, 30, 32, 34, 36, 38, 40, 42, 44])
player3_goals = np.array([9, 10, 12, 14, 16, 18, 20, 22, 24, 26])

def print_player_stats(player_name, salary, appearances, goals):
    salary_sum = np.sum(salary)
    appearances_sum = np.sum(appearances)
    goals_sum = np.sum(goals)

    print(f"{player_name} - Total Salary: {salary_sum}, Total Appearances: {appearances_sum}, Total Goals: {goals_sum}")

print_player_stats("Player 1", player1_salary, player1_appearances, player1_goals)
print_player_stats("Player 2", player2_salary, player2_appearances, player2_goals)
print_player_stats("Player 3", player3_salary, player3_appearances, player3_goals)

Player 1 - Total Salary: 690000, Total Appearances: 280, Total Goals: 98
Player 2 - Total Salary: 649000, Total Appearances: 270, Total Goals: 86
Player 3 - Total Salary: 790000, Total Appearances: 346, Total Goals: 171
